version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: astra-shop-php
    working_dir: /var/www/html
    volumes:
      - ./astra-shop-backend:/var/www/html
      - ./astra-shop-backend/vendor:/var/www/html/vendor
      - ./astra-shop-backend/storage:/var/www/html/storage
      - ./astra-shop-backend/storage/app/public/storage:/var/www/html/public/storage
      - ./astra-shop-backend/cache:/var/www/html/bootstrap/cache
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: astra-shop-nginx
    ports:
      - "8090:80"  # Changed to 8080 to avoid conflict
    volumes:
      - ./astra-shop-backend:/var/www/html
      - ./astra-shop-backend/storage/app/public/storage:/var/www/html/public/storage
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  node:
    build: ./docker/node
    container_name: astra-shop-node
    working_dir: /var/www/html
    command: sh -c "npm install && npm run prod"
    volumes:
      - ./astra-shop-backend:/var/www/html
    ports:
      - "5173:5173"

  queue:
    build: ./docker/php
    container_name: astra-shop-queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --verbose --queue=default
    volumes:
      - ./astra-shop-backend:/var/www/html
    depends_on:
      - redis
      - php
      - db

  db:
    image: mysql:8.4
    container_name: astra-shop-mysql
    environment:
      MYSQL_DATABASE: astra-shop
      MYSQL_USER: astra-shop
      MYSQL_PASSWORD: astra-shop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Changed to avoid conflict with Astra
    volumes:
      - astra-shop_mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: astra-shop-redis
    ports:
      - "6380:6379"  # Changed to avoid conflict
    volumes:
      - astra-shop_redis_data:/data

volumes:
  astra-shop_mysql_data:
  astra-shop_redis_data:
